releases:
 - name: adservice
   chart: charts/microservices
   values:
    - values/adservice_values.yaml
 
 - name: cartservice
   chart: charts/microservices
   values:
    - values/cartservice_values.yaml

 - name: checkoutservice
   chart: charts/microservices
   values:
    - values/checkoutservice_values.yaml

 - name: currencyservice
   chart: charts/microservices
   values:
    - values/currencyservice_values.yaml

 - name: emailservice
   chart: charts/microservices
   values:
    - values/emailservice_values.yaml
  
 - name: paymentservice
   chart: charts/microservices
   values:
    - values/paymentservice_values.yaml

 - name: productcatalogservice
   chart: charts/microservices
   values:
    - values/productcatalogservice_values.yaml

 - name: recommendationservice
   chart: charts/microservices
   values:
    - values/recommendationservice_values.yaml

 - name: shippingservice
   chart: charts/microservices
   values:
    - values/shippingservice_values.yaml

 - name: redis
   chart: charts/redis
   values:
    - values/redis_values.yaml

 - name: frontend
   chart: charts/microservices
   values:
    - values/frontend_values.yaml